### ISSUE TITLE
OpenMMException: CustomCentroidBondForce: Weights for group 0 add to 0

### ISSUE THREAD

**Issue by evamartin1240** [openmm/openmm#4091]
I am using this code:

```
k = 0*unit.kilojoules_per_mole  # NOTE - 0 kJ/mol constant
upper_wall = 10.00*unit.nanometer
fb_eq = '(k/2)*max(distance(g1,g2) - upper_wall, 0)^2'
upper_wall_rest = openmm.CustomCentroidBondForce(2, fb_eq)
upper_wall_rest.addGroup(lig_ha_idx)
upper_wall_rest.addGroup(anchor_atom_idx)
upper_wall_rest.addBond([0, 1])
upper_wall_rest.addGlobalParameter('k', k)
upper_wall_rest.addGlobalParameter('upper_wall', upper_wall)
upper_wall_rest.setUsesPeriodicBoundaryConditions(True)
system.addForce(upper_wall_rest)

simulation = Simulation(parm.topology, system, integrator, platform)
```
And I am getting the following error:

`OpenMMException: CustomCentroidBondForce: Weights for group 0 add to 0`

**Comment by peastman** [comment]
Can you provide a complete example that reproduces the problem?  That means a complete script and all necessary input files.  Thanks!

**Comment by evamartin1240** [comment]
The necessary files can be found in the following link (the error arrises in the `produce` function): https://github.com/ProtStructurePrep/protein_structure_preparation/tree/develop/openbpmd

**Comment by jeff231li** [comment]
@evamartin1240 what happens with you modify this line
```
upper_wall_rest.addBond([0, 1])
```
to 
```
upper_wall_rest.addBond([0, 1], [])
```

If the above does not work I'm guessing the problem is that the masses is equal to zero in `weights`. If this is the case then changing the lines
```
upper_wall_rest.addGroup(lig_ha_idx)
upper_wall_rest.addGroup(anchor_atom_idx)
```
to the one below should solve this issue
```
upper_wall_rest.addGroup(lig_ha_idx, [1.0 for i in range(len(lig_ha_idx))])
upper_wall_rest.addGroup(anchor_atom_idx, [1.0 for i in range(len(anchor_atom_idx))])
```

**Comment by evamartin1240** [comment]
Thanks for your help! I have tried both options and I am still getting the same error:
`OpenMMException: CustomCentroidBondForce: Weights for group 0 add to 0`

**Comment by jeff231li** [comment]
hmm, can you check if both `lig_ha_idx` and `anchor_atom_idx` are not an empty list.

**Comment by evamartin1240** [comment]
Yes, you are right. `lig_ha_idx` was empty and this was causing the problem. Thanks for your help, now I know what is happenning!
