### ISSUE TITLE
PeriodicTorsionForce on virtual sites and simulation.context.setVelocitiesToTemperature used together are unstable

### ISSUE THREAD

**Issue by advaitathreya** [openmm/openmm#4477]
I'm running into an issue where if there is a PeriodicTorsionForce added to the system between TwoParticleAverageSite virtual sites, _and_ I setVelocitiesToTemperature before running a simulation, I have an unstable system with really high temperatures. Removing the dihedral, _or_ not setting velocities to temperature and allowing it to equilibrate up to the temperature, both resolve this issue. Note that this is happening even when the dihedral force constant is set to 0, so there should be no forces acting on the system.

Below is an example that produces this issue for me:

```
import sys
import numpy as np
import openmm.app
from openmm import unit

use_dihedral = True
use_velocities = True

num_monomers = 20

length_scale = 1.0 * unit.nanometer
bond_length = 15.0 * length_scale
monomer_diameter = 5.0 * length_scale
sticker_diameter = 2.0 * length_scale
sticker_offset = monomer_diameter / 2

sim_dt = 1e-5 * unit.picosecond
n_steps_simulation = 10
save_freq = 1
damp = 0.5 / unit.picosecond

elemA = openmm.app.element.Element(0, 'A0', 'A0', 1 * unit.amu)
elemS = openmm.app.element.Element(0, 'S0', 'S0', 1 * unit.amu)

top = openmm.app.topology.Topology()
chain = top.addChain(id='C')
residue = top.addResidue('R', chain)
sets_of_indices_for_each_monomer = []
for i in range(num_monomers):
    if i == 0:
        atom0 = top.addAtom(f'A{i}', elemA, residue)
        stic00 = top.addAtom(f'S0{i}', elemS, residue)
        stic01 = top.addAtom(f'S1{i}', elemS, residue)
        sets_of_indices_for_each_monomer.append((stic00.index, atom0.index, stic01.index))
        continue
    atom1 = top.addAtom(f'A{i}', elemA, residue)
    stic10 = top.addAtom(f'S0{i}', elemS, residue)
    stic11 = top.addAtom(f'S1{i}', elemS, residue)
    sets_of_indices_for_each_monomer.append((stic10.index, atom1.index, stic11.index))
    bond = top.addBond(atom0, atom1)
    atom0 = atom1
sets_of_indices_for_each_monomer = np.array(sets_of_indices_for_each_monomer, dtype=int)
bead_positions = np.zeros((num_monomers, 3), dtype=int)
bead_positions[:, 0] = np.arange(num_monomers)
bead_positions -= bead_positions.mean(axis=0, dtype=int)
positions = np.zeros((top.getNumAtoms(), 3)) * unit.nanometer
for i, idxes in enumerate(sets_of_indices_for_each_monomer):
    pu, pv, pd = idxes
    positions[pv] = bead_positions[i] * bond_length
    positions[pu] = positions[pv] - np.array([0, 0, sticker_offset.value_in_unit(unit.nanometer)]) * length_scale
    positions[pd] = positions[pv] + np.array([0, 0, sticker_offset.value_in_unit(unit.nanometer)]) * length_scale

initial_box_length = np.ptp(positions.value_in_unit(unit.nanometer), axis=0).max() * 2 * length_scale.value_in_unit(unit.nanometer)
top.setUnitCellDimensions((initial_box_length, initial_box_length, initial_box_length))
positions = [openmm.vec3.Vec3(*p) for p in positions]

T = 1 * unit.kilojoule_per_mole / (unit.BOLTZMANN_CONSTANT_kB * unit.AVOGADRO_CONSTANT_NA)
k_BT = T * unit.BOLTZMANN_CONSTANT_kB * unit.AVOGADRO_CONSTANT_NA

forces = []

n14_dihedral = np.pi / 2
k_n14_dihedral = 0
dihedral = openmm.openmm.PeriodicTorsionForce()
for i, j, k, l in np.lib.stride_tricks.sliding_window_view(sets_of_indices_for_each_monomer[:, 1], 4):
    dihedral.addTorsion(i, j, k, l, 1, n14_dihedral, k_n14_dihedral * k_BT.value_in_unit(unit.kilojoule_per_mole))
if use_dihedral:
    forces.append(dihedral)

constraints, virtual_sites = [], []
for i, idxes in enumerate(sets_of_indices_for_each_monomer):
    pu, pv, pd = idxes
    distance = unit.norm(positions[pd] - positions[pu])
    constraints.append((pu, pd, distance))
    virtual_sites.append((pv, (pu, pd, 0.5, 0.5)))

ff = openmm.app.forcefield.ForceField()

def generator(forcefield, residue):
    template = forcefield._TemplateData(residue.name)
    for a in residue.atoms():
        forcefield.registerAtomType({'name': a.name, 'class': a.element.symbol[0], 'element': a.element.symbol, 'mass': a.element.mass.value_in_unit(unit.amu)})
        tad = forcefield._TemplateAtomData(a.name, a.name, a.element)
        template.addAtom(tad)
    for b in residue.bonds():
        template.addBond(b[0].index, b[1].index)
    forcefield.registerResidueTemplate(template)
    return True

ff.registerTemplateGenerator(generator)

system = ff.createSystem(top)

for i, force in enumerate(forces):
    system.addForce(force)

for c in constraints:
    system.addConstraint(*c)

for k, v in virtual_sites:
    system.setVirtualSite(k, openmm.openmm.TwoParticleAverageSite(*v))
    system.setParticleMass(k, 0)

integrator = openmm.LangevinIntegrator(T, damp, sim_dt)

platform = openmm.Platform.getPlatformByName('CUDA')
properties = {'CudaPrecision': 'double'}
simulation = openmm.app.Simulation(top, system, integrator, platform, properties)
simulation.context.setPositions(positions)
if use_velocities:
    simulation.context.setVelocitiesToTemperature(T)
simulation.context.applyConstraints(tol=1e-6)
simulation.context.applyVelocityConstraints(tol=1e-6)
simulation.minimizeEnergy()

simulation.reporters.append(openmm.app.StateDataReporter(sys.stdout, save_freq, potentialEnergy=True, kineticEnergy=True, totalEnergy=True, temperature=True, step=True, separator='\t\t'))

simulation.step(n_steps_simulation)
```

Output from this script with `use_dihedral = True; use_velocities = True`:
```
#"Step"		"Potential Energy (kJ/mole)"		"Kinetic Energy (kJ/mole)"		"Total Energy (kJ/mole)"		"Temperature (K)"
1		0.0		276728326.8654269		276728326.8654269		686242630.4976941
2		0.0		276725583.342575		276725583.342575		686235826.9934776
3		0.0		276722910.5608061		276722910.5608061		686229198.9159957
4		0.0		276720187.0504005		276720187.0504005		686222445.0394913
5		0.0		276717393.071361		276717393.071361		686215516.4118828
6		0.0		276714567.19464624		276714567.19464624		686208508.6830673
7		0.0		276711797.9307719		276711797.9307719		686201641.3451724
8		0.0		276709026.2691761		276709026.2691761		686194768.0613064
9		0.0		276706343.016522		276706343.016522		686188114.0176798
10		0.0		276703572.564654		276703572.564654		686181243.7337478
```

Output with `use_dihedral = False; use_velocities = True`:
```
#"Step"		"Potential Energy (kJ/mole)"		"Kinetic Energy (kJ/mole)"		"Total Energy (kJ/mole)"		"Temperature (K)"
1		0.0		51.865461627508516		51.865461627508516		128.61816938801212
2		0.0		51.8560879113737		51.8560879113737		128.59492404955776
3		0.0		51.9106320070181		51.9106320070181		128.73018480908
4		0.0		51.92181375062037		51.92181375062037		128.7579137706579
5		0.0		51.8919813180766		51.8919813180766		128.6839340403756
6		0.0		51.92224834706875		51.92224834706875		128.75899150134532
7		0.0		51.96399149128399		51.96399149128399		128.8625079191114
8		0.0		52.02248624487836		52.02248624487836		129.00756568761528
9		0.0		51.979477205529946		51.979477205529946		128.90091004945944
10		0.0		51.98646696879658		51.98646696879658		128.9182435605784
```

Output with `use_dihedral = True; use_velocities = False`. Note that here I run for 1000000 steps first before logging:
```
#"Step"		"Potential Energy (kJ/mole)"		"Kinetic Energy (kJ/mole)"		"Total Energy (kJ/mole)"		"Temperature (K)"
1000001		0.0		36.98979555032528		36.98979555032528		91.72886233786744
1000002		0.0		36.977561236232646		36.977561236232646		91.69852316738798
1000003		0.0		36.99494350815587		36.99494350815587		91.74162846182507
1000004		0.0		36.9549987174482		36.9549987174482		91.64257167728691
1000005		0.0		36.926546270254235		36.926546270254235		91.5720140931478
1000006		0.0		36.89449812709557		36.89449812709557		91.49253974979854
1000007		0.0		36.89780071001429		36.89780071001429		91.50072963485748
1000008		0.0		36.90332797562567		36.90332797562567		91.51443638232197
1000009		0.0		36.886851826938475		36.886851826938475		91.47357813067984
1000010		0.0		36.87570128646006		36.87570128646006		91.44592654793058
```

I'm using openmm version 7.7.

I'm not sure what might be causing this- I'm able to work around it by just not setting the velocities to the temperature at the start and equilibrating, but it still seems like either I'm defining my forces wrong, or there is some bug (perhaps an overflow error?)

**Comment by peastman** [comment]
Here's what I get with `use_dihedral` and `use_velocities` both set to True.

```
#"Step"		"Potential Energy (kJ/mole)"		"Kinetic Energy (kJ/mole)"		"Total Energy (kJ/mole)"		"Temperature (K)"
1		0.0		48.74110554903746		48.74110554903746		120.87025879935706
2		0.0		48.774221658706665		48.774221658706665		120.95238153131106
3		0.0		48.810002256184816		48.810002256184816		121.04111177303339
4		0.0		48.753695484250784		48.753695484250784		120.90147985416
5		0.0		48.719734236598015		48.719734236598015		120.81726131322417
6		0.0		48.73651236668229		48.73651236668229		120.85886843113033
7		0.0		48.77409961819649		48.77409961819649		120.95207889008282
8		0.0		48.81226063519716		48.81226063519716		121.04671219700028
9		0.0		48.810707949101925		48.810707949101925		121.04286178023087
10		0.0		48.818154357373714		48.818154357373714		121.06132769898258
```

Can you test with the latest release (8.1.1)?  Let's make sure it isn't a problem that has already been fixed in a release.

**Comment by advaitathreya** [comment]
Still the same with OpenMM version 8.1.1...

```
OpenMM version = 8.1.1
#"Step"		"Potential Energy (kJ/mole)"		"Kinetic Energy (kJ/mole)"		"Total Energy (kJ/mole)"		"Temperature (K)"
1		0.0		276717346.6389081		276717346.6389081		686215401.2667185
2		0.0		276714552.30679226		276714552.30679226		686208471.7635362
3		0.0		276711812.84629077		276711812.84629077		686201678.3333081
4		0.0		276709062.16149235		276709062.16149235		686194857.0685929
5		0.0		276706336.42030996		276706336.42030996		686188097.6601137
6		0.0		276703630.31066453		276703630.31066453		686181386.9347516
7		0.0		276700957.56766605		276700957.56766605		686174758.9534146
8		0.0		276698190.3026266		276698190.3026266		686167896.5723151
9		0.0		276695398.841691		276695398.841691		686160974.1892072
10		0.0		276692739.87961835		276692739.87961835		686154380.3823938
```

Would any information about the hardware help? I don't know what would be relevant.

**Comment by z-gong** [comment]
Does it makes any difference if you put `simulation.context.setVelocitiesToTemperature(T)` after `simulation.minimizeEnergy()`?
The `setVelocitiesToTemperature` sets the velocity of atoms after half steps, based the current forces. If the current structure is not at a energy minima, it may results in very large velocities.

**Comment by advaitathreya** [comment]
Ok yes.. Changing the order now works. Curious why @peastman was able to run the script as is without issue still. But thanks @z-gong!

Output:
```
OpenMM version = 7.7
#"Step"		"Potential Energy (kJ/mole)"		"Kinetic Energy (kJ/mole)"		"Total Energy (kJ/mole)"		"Temperature (K)"
1		0.0		40.63674367242579		40.63674367242579		100.77271881959268
2		0.0		40.61942541453714		40.61942541453714		100.72977226987094
3		0.0		40.620588681686726		40.620588681686726		100.73265698903845
4		0.0		40.550058855428624		40.550058855428624		100.55775413739275
5		0.0		40.57160254007301		40.57160254007301		100.61117907942322
6		0.0		40.57216901651554		40.57216901651554		100.61258385170817
7		0.0		40.55180833018856		40.55180833018856		100.5620925590312
8		0.0		40.50148435818526		40.50148435818526		100.43729704092934
9		0.0		40.52547905159577		40.52547905159577		100.49680009835222
10		0.0		40.53017791016611		40.53017791016611		100.50845252693506
```

Script:
```
import sys
import numpy as np
import openmm.app
from openmm import unit

print(f'OpenMM version = {openmm.__version__}')

use_dihedral = True
use_velocities = True

num_monomers = 20

length_scale = 1.0 * unit.nanometer
bond_length = 15.0 * length_scale
monomer_diameter = 5.0 * length_scale
sticker_diameter = 2.0 * length_scale
sticker_offset = monomer_diameter / 2

sim_dt = 1e-5 * unit.picosecond
n_steps_simulation = 10
save_freq = 1
damp = 0.5 / unit.picosecond

elemA = openmm.app.element.Element(0, 'A0', 'A0', 1 * unit.amu)
elemS = openmm.app.element.Element(0, 'S0', 'S0', 1 * unit.amu)

top = openmm.app.topology.Topology()
chain = top.addChain(id='C')
residue = top.addResidue('R', chain)
sets_of_indices_for_each_monomer = []
for i in range(num_monomers):
    if i == 0:
        atom0 = top.addAtom(f'A{i}', elemA, residue)
        stic00 = top.addAtom(f'S0{i}', elemS, residue)
        stic01 = top.addAtom(f'S1{i}', elemS, residue)
        sets_of_indices_for_each_monomer.append((stic00.index, atom0.index, stic01.index))
        continue
    atom1 = top.addAtom(f'A{i}', elemA, residue)
    stic10 = top.addAtom(f'S0{i}', elemS, residue)
    stic11 = top.addAtom(f'S1{i}', elemS, residue)
    sets_of_indices_for_each_monomer.append((stic10.index, atom1.index, stic11.index))
    bond = top.addBond(atom0, atom1)
    atom0 = atom1
sets_of_indices_for_each_monomer = np.array(sets_of_indices_for_each_monomer, dtype=int)
bead_positions = np.zeros((num_monomers, 3), dtype=int)
bead_positions[:, 0] = np.arange(num_monomers)
bead_positions -= bead_positions.mean(axis=0, dtype=int)
positions = np.zeros((top.getNumAtoms(), 3)) * unit.nanometer
for i, idxes in enumerate(sets_of_indices_for_each_monomer):
    pu, pv, pd = idxes
    positions[pv] = bead_positions[i] * bond_length
    positions[pu] = positions[pv] - np.array([0, 0, sticker_offset.value_in_unit(unit.nanometer)]) * length_scale
    positions[pd] = positions[pv] + np.array([0, 0, sticker_offset.value_in_unit(unit.nanometer)]) * length_scale

initial_box_length = np.ptp(positions.value_in_unit(unit.nanometer), axis=0).max() * 2 * length_scale.value_in_unit(unit.nanometer)
top.setUnitCellDimensions((initial_box_length, initial_box_length, initial_box_length))
positions = [openmm.vec3.Vec3(*p) for p in positions]

T = 1 * unit.kilojoule_per_mole / (unit.BOLTZMANN_CONSTANT_kB * unit.AVOGADRO_CONSTANT_NA)
k_BT = T * unit.BOLTZMANN_CONSTANT_kB * unit.AVOGADRO_CONSTANT_NA

forces = []

n14_dihedral = np.pi / 2
k_n14_dihedral = 0
dihedral = openmm.openmm.PeriodicTorsionForce()
for i, j, k, l in np.lib.stride_tricks.sliding_window_view(sets_of_indices_for_each_monomer[:, 1], 4):
    dihedral.addTorsion(i, j, k, l, 1, n14_dihedral, k_n14_dihedral * k_BT.value_in_unit(unit.kilojoule_per_mole))
if use_dihedral:
    forces.append(dihedral)

constraints, virtual_sites = [], []
for i, idxes in enumerate(sets_of_indices_for_each_monomer):
    pu, pv, pd = idxes
    distance = unit.norm(positions[pd] - positions[pu])
    constraints.append((pu, pd, distance))
    virtual_sites.append((pv, (pu, pd, 0.5, 0.5)))

ff = openmm.app.forcefield.ForceField()

def generator(forcefield, residue):
    template = forcefield._TemplateData(residue.name)
    for a in residue.atoms():
        forcefield.registerAtomType({'name': a.name, 'class': a.element.symbol[0], 'element': a.element.symbol, 'mass': a.element.mass.value_in_unit(unit.amu)})
        tad = forcefield._TemplateAtomData(a.name, a.name, a.element)
        template.addAtom(tad)
    for b in residue.bonds():
        template.addBond(b[0].index, b[1].index)
    forcefield.registerResidueTemplate(template)
    return True

ff.registerTemplateGenerator(generator)

system = ff.createSystem(top)

for i, force in enumerate(forces):
    system.addForce(force)

for c in constraints:
    system.addConstraint(*c)

for k, v in virtual_sites:
    system.setVirtualSite(k, openmm.openmm.TwoParticleAverageSite(*v))
    system.setParticleMass(k, 0)

integrator = openmm.LangevinIntegrator(T, damp, sim_dt)

platform = openmm.Platform.getPlatformByName('CUDA')
properties = {'CudaPrecision': 'double'}
simulation = openmm.app.Simulation(top, system, integrator, platform, properties)
simulation.context.setPositions(positions)
simulation.context.applyConstraints(tol=1e-6)
simulation.context.applyVelocityConstraints(tol=1e-6)
simulation.minimizeEnergy()
if use_velocities:
    simulation.context.setVelocitiesToTemperature(T)
simulation.reporters.append(openmm.app.StateDataReporter(sys.stdout, save_freq, potentialEnergy=True, kineticEnergy=True, totalEnergy=True, temperature=True, step=True, separator='\t\t'))
simulation.step(n_steps_simulation)
```

**Comment by peastman** [comment]
No idea!  But good catch noticing that.
